In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.__config__.show())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/petri/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/petri/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/petri/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/petri/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/petri/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/petri/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/petri/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/petri/anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
x = np.zeros((10, 10))
print(x.size * x.itemsize)

800


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
# In kernel:
    # np.info(np.add)
# With bash:
    # %run `python -c "import numpy; numpy.info(numpy.add)"`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
x = np.arange(10, 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
x = x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
answer(10)

nz = np.nonzero([1,2,0,0,4,0])
print(nz)


In [12]:
x = np.array([1,2,0,0,4,0])
print(np.nonzero(x))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
x = np.random.random((3,3,3))
print(x)

[[[0.52179032 0.15533445 0.16717282]
  [0.59929555 0.80479952 0.99706563]
  [0.92490766 0.85932151 0.35517239]]

 [[0.75295783 0.87315444 0.11265448]
  [0.8806324  0.06493922 0.57520711]
  [0.09835777 0.96695685 0.39374811]]

 [[0.80117919 0.72003118 0.92210549]
  [0.71938687 0.45287244 0.95315182]
  [0.39766916 0.42255395 0.17758156]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
x = np.random.random((10,10))
print(np.max(x))
print(np.min(x))

0.9768110966786768
0.012978642915750904


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
x = np.random.random(30)
print(np.mean(x))

0.4724546646058238


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
x = np.ones((10,10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
x = np.ones((10,10))
x[:, [0,-1]] = 0
x[[0,-1], :] = 0
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
x = np.diag(1+np.arange(4), k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
x = np.zeros((8,8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
x = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
x = np.random.random((5,5))
x = (x - np.mean(x))/np.std(x)
print(x)

[[-1.57925414  0.81917035  1.52642967  1.13880585 -0.20869789]
 [-1.09253531 -1.3637397   1.36886414  1.11196677 -1.25946974]
 [ 0.0031725  -0.94697655  0.51988032  1.00643019 -1.31531636]
 [-0.67666756  0.61031761 -0.00534614 -1.32433151  0.41422129]
 [ 0.40903657 -0.71468658  1.68608459  0.26770888 -0.39506724]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
x = np.ones((5,3))
y = np.ones((3,2))
z = np.dot(x, y)
# z = x @ y
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
x = np.arange(10)
x[(x>3) & (x<8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
Z = np.arange(10)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# The final one is ambiguous
# Z<Z>Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-30-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-30-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [31]:
x = np.random.uniform(-10, 10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([  3.,  -1.,  -4.,  -1.,   2.,   4.,  -6., -10.,   2.,  -7.])

#### 30. How to find common values between two arrays? (★☆☆)

In [32]:
x = np.random.randint(0, 10, 10)
y = np.random.randint(0, 10, 10)
print(np.intersect1d(x,y))

[1 2 3 5 6 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [33]:
# Zero warnings
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Turn warnings back on
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-34-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2021-09-18 2021-09-19 2021-09-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [36]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [37]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [38]:
x = np.random.uniform(0, 10, 10)
print(x - x%1)
print(x // 1)
print(np.floor(x))
print(x.astype(int))
print(np.trunc(x))

[3. 0. 2. 8. 1. 1. 8. 7. 7. 5.]
[3. 0. 2. 8. 1. 1. 8. 7. 7. 5.]
[3. 0. 2. 8. 1. 1. 8. 7. 7. 5.]
[3 0 2 8 1 1 8 7 7 5]
[3. 0. 2. 8. 1. 1. 8. 7. 7. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
x = np.zeros((5, 5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [40]:
x = np.fromiter(range(10),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [41]:
x = random.random(10)
print(x)

[0.42193336 0.59113172 0.21223721 0.71280727 0.65578094 0.41060778
 0.80308191 0.8624112  0.58996632 0.33586968]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [42]:
x = random.random(10)
x.sort()
print(x)

[0.21893018 0.2590685  0.45004086 0.52429381 0.66692737 0.73284563
 0.74408918 0.7510762  0.83426028 0.99793425]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
x = np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [44]:
x = np.random.randint(0, 10, 10)
y = np.random.randint(0, 10, 10)

# Tolerance
equal = np.allclose(x, y)
print(equal)

# Equality
equal = np.array_equal(x, y)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [45]:
x = np.arange(10)
x.flags.writeable = False
# x[0] = 10

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [46]:
x = np.random.random((10,2))
X,Y = x[:,0], x[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.55771997 0.73058084 0.53682291 0.96079086 1.0957736  0.40039102
 0.90162227 0.78423668 0.67027893 0.99926385]
[0.59096937 0.48462048 0.53287065 0.91372705 1.14956722 0.23989818
 1.31555463 0.3149144  0.08503366 0.81130198]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [47]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.4169893  0.77316477 0.02032551 0.48034264 0.         0.88601812
 0.55336303 0.52771793 0.01496968 0.08882322]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [48]:
x = np.zeros((5,5), [('x',float),('y',float)])
x['x'], x['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(x)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [49]:
x = np.random.random(10)
y = np.random.random(10)
c = 1 / np.subtract.outer(x, y)
print(c)

[[  17.42822716    4.61114324   -2.69003138   -7.98977494    1.69087939
     1.68790176    2.07182424    2.35099185   15.05077375   -3.0987178 ]
 [   2.34201572    1.70511591 -467.63036311    4.09090877    1.04056901
     1.03944056    1.17333591    1.25792995    2.29333497   21.32636754]
 [  -5.91968916 -105.93206099   -1.67210422   -2.84522589    2.73895862
     2.73115416    3.90075765    5.02395377   -6.25530902   -1.82142696]
 [   3.08271761    2.06664142   -9.54818418    7.04965322    1.16493206
     1.16351795    1.33390719    1.44432841    2.9989262   -17.95228884]
 [   7.27456976    3.36753684   -3.42869819  -22.18624142    1.48921386
     1.48690365    1.77697722    1.97847663    6.82459887   -4.1215506 ]
 [   3.32529808    2.17290833   -7.78839628    8.46118415    1.19795632
     1.19646094    1.3773855     1.49544086    3.22800874  -12.59963387]
 [  -2.05760813   -3.0626613    -1.09275018   -1.49579828   20.82081311
    20.37814954  -16.47095086   -8.47263871   -2.09671032 

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [50]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [51]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((10,10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [52]:
x = np.random.random(100)
k = np.random.random(1)
index = np.abs(x-k).argmin()
print(x[index])

0.030562452756885405
